@host = http://localhost:5291

# Create a game
POST {{host}}/api/games

###
# Get current state (paste an id from the create response)
GET {{host}}/api/games/{{id}}

###
# Submit a move
POST {{host}}/api/games/{{id}}/moves
Content-Type: application/json

{ "column": 3 }